### ISSUE TITLE
Themes, color for Linux mint 21.1 QT5

### ISSUE THREAD

**Issue by robouden** [rncbc/qpwgraph#11]
Great tool for PipeWire routing, but I like to set my own color scheme, is that possible?

Regards,
Rob Oudendijk

**Comment by rncbc** [comment]
please refer to https://gitlab.freedesktop.org/rncbc/qpwgraph/-/issues/61 for a possible solution
also if qpwgraph is built to qt5, you'll need something else like eg. qt5ct ...
thanks
