### ISSUE TITLE
Missing Global Shortcuts Menu

### ISSUE THREAD

**Issue by hugeblank** [rncbc/qpwgraph#12]
It seems the global shortcuts menu to allow me to save/activate patchbay configurations are missing. I'm running on KDE Plasma, and while the DE supplies the user with a global shortcuts widget, I'm not using it, and so I'd expect it to put the menu just below the window decorations.

Screenshot:
![Screenshot_20230214_021430](https://user-images.githubusercontent.com/16393543/218705533-475250c5-a016-4d16-ad3c-22c924039391.png)
Compare this to the screenshot provided in the readme, where the shortcuts bar is between the window decorations and connections menu bar.

System info:
Operating System: Arch Linux
KDE Plasma Version: 5.26.5
KDE Frameworks Version: 5.102.0
Qt Version: 5.15.8
Kernel Version: 6.1.8-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 2700X Eight-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: AMD Radeon RX 6600 XT
Manufacturer: Micro-Star International Co., Ltd.
Product Name: MS-7C37
System Version: 1.0

**Comment by rncbc** [comment]
hit [Ctrl+M] to get the main menu into view; then View > Toolbar > Patchbay to get the toolbar too.

really don't know why you started without the main menu; maybe a Mint "feature" or you toggled it off (Ctrl+M) accidentally sometime before.

**Comment by hugeblank** [comment]
That probably did happen at some point. Thanks for the tip!
Keybindings should probably be documented in the readme.
