### ISSUE TITLE
Feature request - Vumeter

### ISSUE THREAD

**Issue by ogmkp** [rncbc/qpwgraph#15]
Thank you for your great project very usefull!

Is it possible to have a vumeter on the nodes or to have a dynamic highlighting on the lines?
To find out if there is any sound activity.

**Comment by rncbc** [comment]
this is not going to fly, sorry

having a meter, vu, ppm, or anything else for that matter, would need to interfere in the signal path; which means that it would have some intrusion impact on tapping all audio connections paths at least.

unacceptable or else, ou-of-scope to a non-interference management application as qpwgraph poses to be from day one

hyu

**Comment by ogmkp** [comment]
Thanks for your answer, indeed there are limits by design.
I close this request.
