### ISSUE TITLE
Way to force connections to be persistent?

### ISSUE THREAD

**Issue by chrisco23** [rncbc/qpwgraph#16]
I have a strange setup and I tried posting on LinuxMusicians first so I could explain all the details of my question, but no reply (understandable).

Short version:  Is there any way I can force certain connections to persist?  Say I'm just watching youtube or Netflix.  Every time I so much as pause one of them, for about a minute, then hit Play again, I have to go back to qpwgraph and add two extra connections shown here to get the sound routed the way I want (I just want stereo sound but sent to 2 pair of speakers):

https://paste.pics/82336e66adba2b45b8393f775f47c012

Otherwise I got the 4 connections straight across but not the other two.

Things I've tried:
every possible combination of settings on the io4 device I can imagine

Long Version: The image above is simpler than the one I used in my LM post, here: https://linuxmusicians.com/viewtopic.php?p=152544#p152544

But it is the same situation.  Sorry if perhaps this question is more general pipewire than qpwgraph-specific, but I really don't know what else I can do at this point.  Thanks.

**Comment by rncbc** [comment]
you may try saving the desired situation to a Patchbay file and Activate+Exclusive it

hth.

**Comment by chrisco23** [comment]
So far today I've run Youtube and I even broke out a Nektar Impact  LX MINI and everything is staying as I like!

Thanks once again!
