### ISSUE TITLE
Background defaults to white if View: BackgroundColor is pure black

### ISSUE THREAD

**Issue by pranshuthegamer** [rncbc/qpwgraph#2]
try setting the background color of view in qt to 0,0,0
it defaults to white

**Comment by rncbc** [comment]
please use official issue tracker in https://gitlab.freedesktop.org/rncbc/qpwgraph/-/issues

otoh. it is not clear how you're actually trying changing the background color: is it about changing the DE's color-theme or is it by altering the source code?
