### ISSUE TITLE
Taskbar icon not showing in dark (default) Kubuntu theme

### ISSUE THREAD

**Issue by mxa** [rncbc/qpwgraph#23]
Sadly the Icon in the Taskbar is not showing up in the KDE default Kubuntu is using.

Instead there is a clickable gap, if you know what the gap is, it kind of works ;)
![grafik](https://github.com/rncbc/qpwgraph/assets/1220707/b8b6f564-b717-439e-aaec-57502540d758)

**Comment by rncbc** [comment]
install libqt6svg6

**Comment by mxa** [comment]
Thanks Rui!
