### ISSUE TITLE
feature request: hide by type

### ISSUE THREAD

**Issue by windowsrefund** [rncbc/qpwgraph#26]
For example, I have no interest in seeing Alsa devices. Extrapolating on this, I could see how the feature would be useful in the event you'd want to focus on audio connections or something. Especially given the fact layouts are currently not saved. Anything that can be done to reduce clutter would probably go a long way.

At a minimum, I'd envision another entry under the View menu which would then show a submenu where each type is listed along with a checkbox that could be toggled.

**Comment by rncbc** [comment]
> Especially given the fact layouts are currently not saved. 

what? node positions are persistant and have been always saved! what you mean?

ps.  please resort to the official issue tracker (https://gitlab.freedesktop.org/rncbc/qpwgraph/-/issues); GH is not the one.

**Comment by windowsrefund** [comment]
About node positions, I think I confused the impact of #22 

About where issues are maintained. It is unnatural to maintain issues for projects like qtractor here and others under the rnbc umbrella somewhere else. That said, if you did want to do that, I'd expect this repository to have the issues feature disabled and a link provided in the project's README. 

About the original feature request: ?

**Comment by windowsrefund** [comment]
Somewhat resolved with d20ead47b11683af2e30a1e5d8efc47a8748a8bc
