### ISSUE TITLE
Feature Request: '--noexclusive' flag

### ISSUE THREAD

**Issue by Matthew-Whitlock** [rncbc/qpwgraph#27]
### Feature 
When a qpwgraph session is already running and in exclusive mode, I'd like to be able to disable exclusive mode from the command line. E.g., calling `qpwgraph /path/to/new.qpwgraph` and just not including `--exclusive` or including some flag like `--noexclusive`/`--exclusive=false`.

### Motivation
I have a large set of links that can't be run in exclusive mode, or it will block certain applications from auto connecting. I'd rather not add each application to the list of links as they pop up broken. 

However, I also have one pair of links that I would like to alternate between my headphones or my speakers. One solution would be to make a smaller `unlink_headphones.qpwgraph` that only has that specific pair of links set to my speakers. 

Then I could `qpwgraph --activated --minimized --exclusive unlink_headphones.qpwgraph; sleep 1; qpwgraph --activated --minimized --noexclusive link_speakers.qpwgraph` to force only linking the specific node to speakers, then return to safely maintaining the full set of links.

**Comment by rncbc** [comment]
done in ae0b818

note the "non" prefix instead:  `--nonexclusive`

**Comment by Matthew-Whitlock** [comment]
Works perfect, thanks!
