### ISSUE TITLE
Feature Request - Creating nodes from UI

### ISSUE THREAD

**Issue by Hard7Rock** [rncbc/qpwgraph#3]
Add posibility to create PW nodes like, pulse audio null_sink, or pulse-tunnel  from UI. And possibly set default sink from right click menu

**Comment by rncbc** [comment]
please redirect this to pipewire/wireplumber devs; gpwgraph is NOT a PW/WP configuration editor.

**Comment by Hard7Rock** [comment]
OK, reasonably.
