### ISSUE TITLE
qpwgraph creates empty file in home directory

### ISSUE THREAD

**Issue by simvux** [rncbc/qpwgraph#30]
whenever qpwgraph has been launched, the file `qpwgraph:<username>@<hostname>` is created in the root of the home directory. 

the file seems to always be empty. 
is this intended? what's the point of the file?

**Comment by rncbc** [comment]
seems you're running an old build or version...
`qpwgraph -v` ?

**Comment by simvux** [comment]
ah yep, void still packages `0.4.4`. I'll try to get it updated in the repository instead
