### ISSUE TITLE
cli load a patch

### ISSUE THREAD

**Issue by paum3** [rncbc/qpwgraph#31]
Hi, is it possible to load a qpwpatch from commandline?
paum

**Comment by rncbc** [comment]
have you check `qpwgraph --help` ?

**Comment by paum3** [comment]
Hi @rncbc  thanks for reply. Yes, I have checked it - it is no clear for me what I'am doing wrong. when I run ```qpwgraph mypatch.qpwgraph``` which was saved working patchbay, it opens error window with a message: Could not open patchbay file, Sorry.

**Comment by rncbc** [comment]
you must give the correct path, either relative or absolute, eg. `qpwgraph `/path/to/`mypatch.qpwgraph`
