### ISSUE TITLE
renamed ports are positioned incorrectly after relaunch

### ISSUE THREAD

**Issue by 0wsmith** [rncbc/qpwgraph#33]
![20240219005546296772917](https://github.com/rncbc/qpwgraph/assets/18582007/029e631d-3097-4a6d-a34a-590d58be7cb2)

steps:
1. rename a long port name so the width of a client changes
2. fully relaunch qpwgraph
3. only the first channel will be positioned correctly

everything else works, it is just in the wrong position.

versions:
- pipewire 0.3.65-3+deb12u1
- wireplumber 0.4.13-1
- qpwgraph (both 0.3.9-1 and [built from latest commit](/rncbc/qpwgraph/tree/c719826383d2d083fe927282dfedf6c1e6c5e20b))

[cross posted on freedesktop](https://gitlab.freedesktop.org/rncbc/qpwgraph/-/issues/101)

**Comment by rncbc** [comment]
this has  already been addressed at the origin [GL #101](https://gitlab.freedesktop.org/rncbc/qpwgraph/-/issues/101) in https://github.com/rncbc/qpwgraph/commit/c693b660

please don't track on both GH and GL--the later is _The Official_ [repo](https://gitlab.freedesktop.org/rncbc/qpwgraph).
