### ISSUE TITLE
[UI — Question] Fusing lines?

### ISSUE THREAD

**Issue by Atemo-C** [rncbc/qpwgraph#38]
Greetings. As we can see in the image below, output lines for left and right channels are always shown as separate.
![qpwgraph screenshot](https://github.com/rncbc/qpwgraph/assets/160250128/6db30946-b795-433e-8773-ba17acf972fd)

There currently seems to be no way of automatically nor manually combining them into a single line to make things tidier, as shown in this quick-and-dirty, text-only mock-up. *(Other visual differences may be ignored as they are not relevant.)*
![Text-only mock-up](https://github.com/rncbc/qpwgraph/assets/160250128/ceb43bad-058c-401e-9de0-fca7a4a8923e)

Do you think there would be any point in implementing something like this? I personally would love the tidiness it would offer, but I could see this being complicated to implement nicely, and it might create issues that I currently am not thinking of, further complicating things.

I would love to hear your thoughts about it. If this is not something you are interested in, you may feel free to close the issue. Otherwise, I guess that MRs from people more skilled than me would be most welcome.

**Comment by rncbc** [comment]
see https://gitlab.freedesktop.org/rncbc/qpwgraph/-/issues/103 (closed)

**Comment by Atemo-C** [comment]
Ah, I see. Well, thank you! Closing as not planned. Cheers.
