### ISSUE TITLE
qpwgraph can't run dark theme in wayland

### ISSUE THREAD

**Issue by nukeCrayon** [rncbc/qpwgraph#4]
I tried to run it like this: 

QT_QPA_PLATFORM=xcb qpwgraph

But it says some error like this:

QApplication: invalid style override 'Adwaita-Dark' passed, ignoring it.
	Available styles: Windows, Fusion

**Comment by rncbc** [comment]
then try `qpwgraph -style Fusion`

**Comment by nukeCrayon** [comment]
> then try `qpwgraph -style Fusion`
> 
> ps. mind you it's not about wayland but your desktop environment here been doing it on kwin_wayland for almost 2y+, no issues to date with dark color themes.

I tried the `qpwgraph -style Fusion` and still not getting the dark theme.

**Comment by rncbc** [comment]
as said, it's DE related; check whether some qt style/theme package is missing there, possibly named after Adwaita or else...
or try to configure your DE to support qt applications as well on the same qt major version that qpwgraph is built (ie. whether it's  qt5 or qt6).

again, this issue all not related or to blame qpwgraph per se, it is more about your specific DE configuration and/or support.

**Comment by nukeCrayon** [comment]
> as said, it's DE related; check whether some qt style/theme package is missing there, possibly named after Adwaita or else... or try to configure your DE to support qt applications as well on the same qt major version that qpwgraph is built (ie. whether it's qt5 or qt6).
> 
> again, this issue all not related or to blame qpwgraph per se, it is more about your specific DE configuration and/or support.

I found the solution in reddit. for anyone who is also having trouble with this software theming in arch linux wayland/swaywm. please install  **qt6-wayland** and **adwaita-qt6**. As you can see from the comment, the owner is not helpful and always passing the blame from the Desktop Environment that you are using. He don't know whats the requirement dependencies of his creation. Useful application nonetheless.

**Comment by rncbc** [comment]
> As you can see from the comment, the owner is not helpful and always passing the blame from the Desktop Environment that you are using. He don't know what's the requirement dependencies of his creation. Useful application nonetheless.

none of those is a requirement of my creation, thank you

as you probably are now aware qt6-wayland and adwaita-qt6 are in fact what is suggested by me here:

> check whether some qt style/theme package is missing there, possibly named after Adwaita or else... or try to configure your DE to support qt applications as well on the same qt major version that qpwgraph is built (ie. whether it's qt5 or qt6).

those packages aren't needed to run qpwgraph at all whatsoever.
