### ISSUE TITLE
Version Mismatch in qpwgraph 0.7.6

### ISSUE THREAD

**Issue by Rutpiv** [rncbc/qpwgraph#43]
Hi there!

I noticed that the package version 0.7.6 is still showing version 0.7.5 in both the build output and the package info. It seems like the CMakeLists.txt file might not have been updated to reflect the new version number. Could you please take a look and update it?

**Comment by rncbc** [comment]
ouch, you're right, but that will need a brand new release, say v0.7.7

will make it soon, thanks

**Comment by Rutpiv** [comment]
Thanks for the quick fix and release of version 0.7.7. Everything is working perfectly now, and I appreciate your attention to correcting the issue!
