### ISSUE TITLE
Cannot give root access to qwgraph (flatpak ID + file format conflict)

### ISSUE THREAD

**Issue by yioannides** [rncbc/qpwgraph#44]
If a user wants to give qpwgraph access to a root folder (like `mnt` for example) via Flatseal to save one's configuration, Flatseal usually creates an override file located in `$USER/.local/share/flatpak/overrides`, but due a conflict between the flatpak ID and file format of qpwgraph ending both in `.qpwgraph`, the override file becomes a qpwgraph configuration file, instead of a text file containing the folder access permission set by Flatpak.

It might be a good idea to maybe set the file format extension to a symbolic name, like `.qpw` or `.qpwconf`

![image](https://github.com/user-attachments/assets/59beb73e-239d-447c-ae0a-b0170899173e)

**Comment by rncbc** [comment]
as this sems to be a flatpak related issue, please proceed to https://github.com/flathub/org.rncbc.qpwgraph/issues

byee

**Comment by yioannides** [comment]
The original issue was more with the actual file format extension conflicting with the flatpak, but it's not a problem, I will use the native package of qpwgraph from now on, thank you
