### ISSUE TITLE
feature request ? show connections maintened by active patch

### ISSUE THREAD

**Issue by rubberplayer** [rncbc/qpwgraph#45]
It would be nice if the connections maintained by the active patch were signaled graphically (by a specific link outline color for instance).  

Thanks for all your excellent music software btw !

**Comment by rncbc** [comment]
they already are when in Edit mode: pinned (aka active) connection lines are shown in bright normal colors and dimmed otherwise.

**Comment by rubberplayer** [comment]
Oh, ok. Did this feature appear happen after 0.3.9 (the version used in debian stable) ? I might be missing something but it does not seem to be the case in this version : even in edit mode, the lines have the same brightness whether they're part of a named patch or not.

**Comment by rncbc** [comment]
well, v0.3.9 is way too old to care; please update to v0.7.7+

you may always stay up-to-date if you go with yours truly [repos](https://www.rncbc.org/drupal/node/2145)

on debian 12 aka bookwork you'll be fine with [Applications (jammy)](https://launchpad.net/~rncbc/+archive/ubuntu/apps-jammy)

enjoy.

**Comment by rubberplayer** [comment]
Fine ! Thank you.
