### ISSUE TITLE
Documentation / Explanation

### ISSUE THREAD

**Issue by hoergen** [rncbc/qpwgraph#7]
Hi I am searching for a documentation or some explanation about some features, that are not intuitive or self explanatory  like

- Activated
- Exclusive
- Pin / Unpin (when are they available?)

Reason is, that I want to save a Snapshot of a current wirering (with some modules of Easy Effects not in linear order) But every time I restart my computer, load the saved patchbay I have to rewire everything. I would love if qpwgraph could remember all connections and disconnections I made, so I have it exact connections, when I saved everything. Is there a way?

**Comment by rncbc** [comment]
hi, you're welcome of course, though you should make it to the official tracker which is on https://gitlab.freedesktop.org/rncbc/qpwgraph and not here
sorry, hyh.
ps. have a look at https://gitlab.freedesktop.org/rncbc/qpwgraph/-/issues/50

**Comment by hoergen** [comment]
Oh thank you :sunflower:  I close this thread then.
