### ISSUE TITLE
FR: Configuring output delays

### ISSUE THREAD

**Issue by Dietr1ch** [rncbc/qpwgraph#9]
I just tried out qpwgraph and got a couple speakers playing audio from the same source.

It's really cool to have the same stream in the whole house, but I noticed there's a ~400ms latency gap between the speakers. Is there a way of adjusting for that delay? I'm not sure if pipewire supports that in the first place, but it'd be nice to get this fixed

**Comment by rncbc** [comment]
probably not in scope to qpwgraph; please try:
  https://gitlab.freedesktop.org/pipewire/pipewire/-/issues
also, re. qpwgraph issues, which this one doesn't seem to be of the kind, please report to:
  https://gitlab.freedesktop.org/rncbc/qpwgraph/-/issues
nb. fyi. here is just a mirror, not the "official" project place.
cheers
